require 'csv'  # => true


data_dir = File.expand_path '../data', __dir__                             # => "/Users/patwey/code/headcount/data"
filenames = Dir.glob("#{data_dir}/*")                                      # => ["/Users/patwey/code/headcount/data/3rd grade students scoring proficient or above on the CSAP_TCAP.csv", "/Users/patwey/code/headcount/data/4th grade students scoring proficient or advanced on CSAP_TCAP.csv", "/Users/patwey/code/headcount/data/8th grade students scoring proficient or above on the CSAP_TCAP.csv", "/Users/patwey/code/headcount/data/Average proficiency on the CSAP_TCAP by race_ethnicity_ Math.csv", "/Users/patwey/code/headcount/data/Average proficiency on the CSAP_TCAP by race_ethnicity_ Reading.csv", "/Users/patwey/code/headcount/data/Average proficiency on the CSAP_TCAP by race_ethnicity_ Writing.csv", "/Users/patwey/code/headcount/data/Dropout rates by race and ethnicity.csv", "/Users/patwey/code/headcount/data/High school graduation rates.csv", "/Users/patwey/code/headcount/data/Kindergartners in full-day program.csv", "/Users/patwey/code/headcount/data/Median household income.csv", "/...
first_filename = "/Users/patwey/code/headcount/data/Pupil enrollment.csv"  # => "/Users/patwey/code/headcount/data/Pupil enrollment.csv"

# all files
results = CSV.read(first_filename, headers: true, header_converters: :symbol).flat_map { |row| row.to_h }  # => [{:location=>"Colorado", :timeframe=>"2009", :dataformat=>"Number", :data=>"832368"}, {:location=>"Colorado", :timeframe=>"2010", :dataformat=>"Number", :data=>"843316"}, {:location=>"Colorado", :timeframe=>"2011", :dataformat=>"Number", :data=>"854265"}, {:location=>"Colorado", :timeframe=>"2012", :dataformat=>"Number", :data=>"863561"}, {:location=>"Colorado", :timeframe=>"2013", :dataformat=>"Number", :data=>"876999"}, {:location=>"Colorado", :timeframe=>"2014", :dataformat=>"Number", :data=>"889006"}, {:location=>"ACADEMY 20", :timeframe=>"2009", :dataformat=>"Number", :data=>"22620"}, {:location=>"ACADEMY 20", :timeframe=>"2010", :dataformat=>"Number", :data=>"23119"}, {:location=>"ACADEMY 20", :timeframe=>"2011", :dataformat=>"Number", :data=>"23657"}, {:location=>"ACADEMY 20", :timeframe=>"2012", :dataformat=>"Number", :data=>"23973"}, {:location=>"ACADEMY 20", :tim...

# group by filename

# group by district name
districts = results.group_by { |x| x[:location] }  # => {"Colorado"=>[{:location=>"Colorado", :timeframe=>"2009", :dataformat=>"Number", :data=>"832368"}, {:location=>"Colorado", :timeframe=>"2010", :dataformat=>"Number", :data=>"843316"}, {:location=>"Colorado", :timeframe=>"2011", :dataformat=>"Number", :data=>"854265"}, {:location=>"Colorado", :timeframe=>"2012", :dataformat=>"Number", :data=>"863561"}, {:location=>"Colorado", :timeframe=>"2013", :dataformat=>"Number", :data=>"876999"}, {:location=>"Colorado", :timeframe=>"2014", :dataformat=>"Number", :data=>"889006"}], "ACADEMY 20"=>[{:location=>"ACADEMY 20", :timeframe=>"2009", :dataformat=>"Number", :data=>"22620"}, {:location=>"ACADEMY 20", :timeframe=>"2010", :dataformat=>"Number", :data=>"23119"}, {:location=>"ACADEMY 20", :timeframe=>"2011", :dataformat=>"Number", :data=>"23657"}, {:location=>"ACADEMY 20", :timeframe=>"2012", :dataformat=>"Number", :data=>"23973"}, {:location=>"ACADEMY 20", :timeframe=>"2013", :dataformat...
districts["Colorado"]                              # => [{:location=>"Colorado", :timeframe=>"2009", :dataformat=>"Number", :data=>"832368"}, {:location=>"Colorado", :timeframe=>"2010", :dataformat=>"Number", :data=>"843316"}, {:location=>"Colorado", :timeframe=>"2011", :dataformat=>"Number", :data=>"854265"}, {:location=>"Colorado", :timeframe=>"2012", :dataformat=>"Number", :data=>"863561"}, {:location=>"Colorado", :timeframe=>"2013", :dataformat=>"Number", :data=>"876999"}, {:location=>"Colorado", :timeframe=>"2014", :dataformat=>"Number", :data=>"889006"}]

# filter by year
data = Hash.new                                   # => {}
districts["Colorado"].each do |hash|              # => [{:location=>"Colorado", :timeframe=>"2009", :dataformat=>"Number", :data=>"832368"}, {:location=>"Colorado", :timeframe=>"2010", :dataformat=>"Number", :data=>"843316"}, {:location=>"Colorado", :timeframe=>"2011", :dataformat=>"Number", :data=>"854265"}, {:location=>"Colorado", :timeframe=>"2012", :dataformat=>"Number", :data=>"863561"}, {:location=>"Colorado", :timeframe=>"2013", :dataformat=>"Number", :data=>"876999"}, {:location=>"Colorado", :timeframe=>"2014", :dataformat=>"Number", :data=>"889006"}]
  data[hash[:timeframe].to_i] = hash[:data].to_i  # => 832368, 843316, 854265, 863561, 876999, 889006
end                                               # => [{:location=>"Colorado", :timeframe=>"2009", :dataformat=>"Number", :data=>"832368"}, {:location=>"Colorado", :timeframe=>"2010", :dataformat=>"Number", :data=>"843316"}, {:location=>"Colorado", :timeframe=>"2011", :dataformat=>"Number", :data=>"854265"}, {:location=>"Colorado", :timeframe=>"2012", :dataformat=>"Number", :data=>"863561"}, {:location=>"Colorado", :timeframe=>"2013", :dataformat=>"Number", :data=>"876999"}, {:location=>"Colorado", :timeframe=>"2014", :dataformat=>"Number", :data=>"889006"}]

data  # => {2009=>832368, 2010=>843316, 2011=>854265, 2012=>863561, 2013=>876999, 2014=>889006}
